<?xml version="1.0" encoding="utf-8"?><Database Name="Database1" Class="DatabaseClasssesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\Database1.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Database1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Employer" Member="Employers">
    <Type Name="Employer">
      <Column Name="EmployerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EmailAddress" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ContactNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AlternativeContactNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ResidentialAddress" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ProfileImage_String" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Employer_Job" Member="Jobs" ThisKey="EmployerID" OtherKey="EmployerID" Type="Job" />
    </Type>
  </Table>
  <Table Name="dbo.JobSeeker" Member="JobSeekers">
    <Type Name="JobSeeker">
      <Column Name="JobSeekerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EmailAddress" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ContactNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AlternativeContactNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ResidentialAddress" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ProfileImage_String" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="IsAvailable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="JobSeeker_InformalSkill" Member="InformalSkills" ThisKey="JobSeekerID" OtherKey="JobSeekerID" Type="InformalSkill" />
      <Association Name="JobSeeker_JobApplication" Member="JobApplications" ThisKey="JobSeekerID" OtherKey="JobSeekerID" Type="JobApplication" />
    </Type>
  </Table>
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="AdminID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EmailAddress" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.InformalSkill" Member="InformalSkills">
    <Type Name="InformalSkill">
      <Column Name="Skill_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="SkillLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="JobSeekerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="JobSeeker_InformalSkill" Member="JobSeeker" ThisKey="JobSeekerID" OtherKey="JobSeekerID" Type="JobSeeker" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.JobApplication" Member="JobApplications">
    <Type Name="JobApplication">
      <Column Name="ApplicationID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="JobID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="JobSeekerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="JobSeeker_JobApplication" Member="JobSeeker" ThisKey="JobSeekerID" OtherKey="JobSeekerID" Type="JobSeeker" IsForeignKey="true" />
      <Association Name="Job_JobApplication" Member="Job" ThisKey="JobID" OtherKey="JobID" Type="Job" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Job" Member="Jobs">
    <Type Name="Job">
      <Column Name="JobID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="NumberOfDays" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StartTime" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EndTime" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ToBePaid" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="EmployerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Job_JobApplication" Member="JobApplications" ThisKey="JobID" OtherKey="JobID" Type="JobApplication" />
      <Association Name="Employer_Job" Member="Employer" ThisKey="EmployerID" OtherKey="EmployerID" Type="Employer" IsForeignKey="true" />
    </Type>
  </Table>
</Database>