<?xml version="1.0" encoding="utf-8"?><Database Name="Database1" Class="userDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\Database1.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Database1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.InformalSkills" Member="InformalSkills">
    <Type Name="InformalSkill">
      <Column Name="Skill_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="UserData_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Userdata_InformalSkill" Member="Userdata" ThisKey="UserData_ID" OtherKey="Id" Type="Userdata" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Userdata" Member="Userdatas">
    <Type Name="Userdata">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="contactNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="alternativeNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="authinticationLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="firstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="lastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ProfileImage_String" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Userdata_InformalSkill" Member="InformalSkills" ThisKey="Id" OtherKey="UserData_ID" Type="InformalSkill" />
      <Association Name="Userdata_Job" Member="Jobs" ThisKey="Id" OtherKey="Employer_ID" Type="Job" />
    </Type>
  </Table>
  <Table Name="dbo.Job" Member="Jobs">
    <Type Name="Job">
      <Column Name="JobID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Duration_Hours" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Reward" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Employer_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Userdata_Job" Member="Userdata" ThisKey="Employer_ID" OtherKey="Id" Type="Userdata" IsForeignKey="true" />
    </Type>
  </Table>
</Database>