<?xml version="1.0" encoding="utf-8"?><Database Name="TempJobs.com_database" Class="UserDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=KAMOGELO;Initial Catalog=TempJobs.com_database;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="TempJobs_com_databaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.UserEmployment" Member="UserEmployments">
    <Type Name="UserEmployment">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="firstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="lastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Adress" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="phoneNumber" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="phoneNumberAlt" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="authinticationLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>