//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prodigy_Employment.DataSR {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataSR.ICollectUserDetailsService1")]
    public interface ICollectUserDetailsService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICollectUserDetailsService1/DoWork", ReplyAction="http://tempuri.org/ICollectUserDetailsService1/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICollectUserDetailsService1/DoWork", ReplyAction="http://tempuri.org/ICollectUserDetailsService1/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICollectUserDetailsService1/getUserInfor", ReplyAction="http://tempuri.org/ICollectUserDetailsService1/getUserInforResponse")]
        System.Data.DataSet getUserInfor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICollectUserDetailsService1/getUserInfor", ReplyAction="http://tempuri.org/ICollectUserDetailsService1/getUserInforResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> getUserInforAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICollectUserDetailsService1Channel : Prodigy_Employment.DataSR.ICollectUserDetailsService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CollectUserDetailsService1Client : System.ServiceModel.ClientBase<Prodigy_Employment.DataSR.ICollectUserDetailsService1>, Prodigy_Employment.DataSR.ICollectUserDetailsService1 {
        
        public CollectUserDetailsService1Client() {
        }
        
        public CollectUserDetailsService1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CollectUserDetailsService1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CollectUserDetailsService1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CollectUserDetailsService1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public System.Data.DataSet getUserInfor() {
            return base.Channel.getUserInfor();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getUserInforAsync() {
            return base.Channel.getUserInforAsync();
        }
    }
}
