//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebApplication1.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService1", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetDataUsingDataContractOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegistrationDatabaseOperationCompleted;
        
        private System.Threading.SendOrPostCallback LgnUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadEmployeesOperationCompleted;
        
        private System.Threading.SendOrPostCallback StoreSkillsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadSkillsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ImageToBase64StringOperationCompleted;
        
        private System.Threading.SendOrPostCallback SingleUserDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostJobOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListOfJobsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChangePasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback ApplyForJobOperationCompleted;
        
        private System.Threading.SendOrPostCallback getApplicationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegistrationDatabaseUpdateOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::WebApplication1.Properties.Settings.Default.WebApplication1_localhost_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetDataUsingDataContractCompletedEventHandler GetDataUsingDataContractCompleted;
        
        /// <remarks/>
        public event RegistrationDatabaseCompletedEventHandler RegistrationDatabaseCompleted;
        
        /// <remarks/>
        public event LgnUserCompletedEventHandler LgnUserCompleted;
        
        /// <remarks/>
        public event ReadEmployeesCompletedEventHandler ReadEmployeesCompleted;
        
        /// <remarks/>
        public event StoreSkillsCompletedEventHandler StoreSkillsCompleted;
        
        /// <remarks/>
        public event ReadSkillsCompletedEventHandler ReadSkillsCompleted;
        
        /// <remarks/>
        public event ImageToBase64StringCompletedEventHandler ImageToBase64StringCompleted;
        
        /// <remarks/>
        public event SingleUserDetailsCompletedEventHandler SingleUserDetailsCompleted;
        
        /// <remarks/>
        public event PostJobCompletedEventHandler PostJobCompleted;
        
        /// <remarks/>
        public event ListOfJobsCompletedEventHandler ListOfJobsCompleted;
        
        /// <remarks/>
        public event ChangePasswordCompletedEventHandler ChangePasswordCompleted;
        
        /// <remarks/>
        public event ApplyForJobCompletedEventHandler ApplyForJobCompleted;
        
        /// <remarks/>
        public event getApplicationsCompletedEventHandler getApplicationsCompleted;
        
        /// <remarks/>
        public event RegistrationDatabaseUpdateCompletedEventHandler RegistrationDatabaseUpdateCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/GetDataUsingDataContract", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CompositeType GetDataUsingDataContract([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] CompositeType composite) {
            object[] results = this.Invoke("GetDataUsingDataContract", new object[] {
                        composite});
            return ((CompositeType)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataUsingDataContractAsync(CompositeType composite) {
            this.GetDataUsingDataContractAsync(composite, null);
        }
        
        /// <remarks/>
        public void GetDataUsingDataContractAsync(CompositeType composite, object userState) {
            if ((this.GetDataUsingDataContractOperationCompleted == null)) {
                this.GetDataUsingDataContractOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataUsingDataContractOperationCompleted);
            }
            this.InvokeAsync("GetDataUsingDataContract", new object[] {
                        composite}, this.GetDataUsingDataContractOperationCompleted, userState);
        }
        
        private void OnGetDataUsingDataContractOperationCompleted(object arg) {
            if ((this.GetDataUsingDataContractCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataUsingDataContractCompleted(this, new GetDataUsingDataContractCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/RegistrationDatabase", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RegistrationDatabase([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string firstName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string lastName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string address, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string cantactNumbers, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string altanativeNumber, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, int authenticationLevel, [System.Xml.Serialization.XmlIgnoreAttribute()] bool authenticationLevelSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string profileImage) {
            this.Invoke("RegistrationDatabase", new object[] {
                        userName,
                        firstName,
                        lastName,
                        address,
                        Email,
                        cantactNumbers,
                        altanativeNumber,
                        password,
                        authenticationLevel,
                        authenticationLevelSpecified,
                        profileImage});
        }
        
        /// <remarks/>
        public void RegistrationDatabaseAsync(string userName, string firstName, string lastName, string address, string Email, string cantactNumbers, string altanativeNumber, string password, int authenticationLevel, bool authenticationLevelSpecified, string profileImage) {
            this.RegistrationDatabaseAsync(userName, firstName, lastName, address, Email, cantactNumbers, altanativeNumber, password, authenticationLevel, authenticationLevelSpecified, profileImage, null);
        }
        
        /// <remarks/>
        public void RegistrationDatabaseAsync(string userName, string firstName, string lastName, string address, string Email, string cantactNumbers, string altanativeNumber, string password, int authenticationLevel, bool authenticationLevelSpecified, string profileImage, object userState) {
            if ((this.RegistrationDatabaseOperationCompleted == null)) {
                this.RegistrationDatabaseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistrationDatabaseOperationCompleted);
            }
            this.InvokeAsync("RegistrationDatabase", new object[] {
                        userName,
                        firstName,
                        lastName,
                        address,
                        Email,
                        cantactNumbers,
                        altanativeNumber,
                        password,
                        authenticationLevel,
                        authenticationLevelSpecified,
                        profileImage}, this.RegistrationDatabaseOperationCompleted, userState);
        }
        
        private void OnRegistrationDatabaseOperationCompleted(object arg) {
            if ((this.RegistrationDatabaseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistrationDatabaseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/LgnUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void LgnUser([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, out int userID, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool userIDSpecified, out bool canLogin, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool canLoginSpecified) {
            object[] results = this.Invoke("LgnUser", new object[] {
                        username,
                        password});
            userID = ((int)(results[0]));
            userIDSpecified = ((bool)(results[1]));
            canLogin = ((bool)(results[2]));
            canLoginSpecified = ((bool)(results[3]));
        }
        
        /// <remarks/>
        public void LgnUserAsync(string username, string password) {
            this.LgnUserAsync(username, password, null);
        }
        
        /// <remarks/>
        public void LgnUserAsync(string username, string password, object userState) {
            if ((this.LgnUserOperationCompleted == null)) {
                this.LgnUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLgnUserOperationCompleted);
            }
            this.InvokeAsync("LgnUser", new object[] {
                        username,
                        password}, this.LgnUserOperationCompleted, userState);
        }
        
        private void OnLgnUserOperationCompleted(object arg) {
            if ((this.LgnUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LgnUserCompleted(this, new LgnUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ReadEmployees", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/TempJobsWcf")]
        public Userdata[] ReadEmployees() {
            object[] results = this.Invoke("ReadEmployees", new object[0]);
            return ((Userdata[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadEmployeesAsync() {
            this.ReadEmployeesAsync(null);
        }
        
        /// <remarks/>
        public void ReadEmployeesAsync(object userState) {
            if ((this.ReadEmployeesOperationCompleted == null)) {
                this.ReadEmployeesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadEmployeesOperationCompleted);
            }
            this.InvokeAsync("ReadEmployees", new object[0], this.ReadEmployeesOperationCompleted, userState);
        }
        
        private void OnReadEmployeesOperationCompleted(object arg) {
            if ((this.ReadEmployeesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadEmployeesCompleted(this, new ReadEmployeesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/StoreSkills", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void StoreSkills([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Name, int UserID, [System.Xml.Serialization.XmlIgnoreAttribute()] bool UserIDSpecified) {
            this.Invoke("StoreSkills", new object[] {
                        Name,
                        UserID,
                        UserIDSpecified});
        }
        
        /// <remarks/>
        public void StoreSkillsAsync(string Name, int UserID, bool UserIDSpecified) {
            this.StoreSkillsAsync(Name, UserID, UserIDSpecified, null);
        }
        
        /// <remarks/>
        public void StoreSkillsAsync(string Name, int UserID, bool UserIDSpecified, object userState) {
            if ((this.StoreSkillsOperationCompleted == null)) {
                this.StoreSkillsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStoreSkillsOperationCompleted);
            }
            this.InvokeAsync("StoreSkills", new object[] {
                        Name,
                        UserID,
                        UserIDSpecified}, this.StoreSkillsOperationCompleted, userState);
        }
        
        private void OnStoreSkillsOperationCompleted(object arg) {
            if ((this.StoreSkillsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StoreSkillsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ReadSkills", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/TempJobsWcf")]
        public InformalSkill[] ReadSkills() {
            object[] results = this.Invoke("ReadSkills", new object[0]);
            return ((InformalSkill[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadSkillsAsync() {
            this.ReadSkillsAsync(null);
        }
        
        /// <remarks/>
        public void ReadSkillsAsync(object userState) {
            if ((this.ReadSkillsOperationCompleted == null)) {
                this.ReadSkillsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadSkillsOperationCompleted);
            }
            this.InvokeAsync("ReadSkills", new object[0], this.ReadSkillsOperationCompleted, userState);
        }
        
        private void OnReadSkillsOperationCompleted(object arg) {
            if ((this.ReadSkillsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadSkillsCompleted(this, new ReadSkillsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ImageToBase64String", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ImageToBase64String([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Image image) {
            object[] results = this.Invoke("ImageToBase64String", new object[] {
                        image});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ImageToBase64StringAsync(Image image) {
            this.ImageToBase64StringAsync(image, null);
        }
        
        /// <remarks/>
        public void ImageToBase64StringAsync(Image image, object userState) {
            if ((this.ImageToBase64StringOperationCompleted == null)) {
                this.ImageToBase64StringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImageToBase64StringOperationCompleted);
            }
            this.InvokeAsync("ImageToBase64String", new object[] {
                        image}, this.ImageToBase64StringOperationCompleted, userState);
        }
        
        private void OnImageToBase64StringOperationCompleted(object arg) {
            if ((this.ImageToBase64StringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ImageToBase64StringCompleted(this, new ImageToBase64StringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/SingleUserDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Userdata SingleUserDetails(int ID, [System.Xml.Serialization.XmlIgnoreAttribute()] bool IDSpecified) {
            object[] results = this.Invoke("SingleUserDetails", new object[] {
                        ID,
                        IDSpecified});
            return ((Userdata)(results[0]));
        }
        
        /// <remarks/>
        public void SingleUserDetailsAsync(int ID, bool IDSpecified) {
            this.SingleUserDetailsAsync(ID, IDSpecified, null);
        }
        
        /// <remarks/>
        public void SingleUserDetailsAsync(int ID, bool IDSpecified, object userState) {
            if ((this.SingleUserDetailsOperationCompleted == null)) {
                this.SingleUserDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSingleUserDetailsOperationCompleted);
            }
            this.InvokeAsync("SingleUserDetails", new object[] {
                        ID,
                        IDSpecified}, this.SingleUserDetailsOperationCompleted, userState);
        }
        
        private void OnSingleUserDetailsOperationCompleted(object arg) {
            if ((this.SingleUserDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SingleUserDetailsCompleted(this, new SingleUserDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/PostJob", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void PostJob([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string description, int duration_hours, [System.Xml.Serialization.XmlIgnoreAttribute()] bool duration_hoursSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string location, double reward, [System.Xml.Serialization.XmlIgnoreAttribute()] bool rewardSpecified, int employerID, [System.Xml.Serialization.XmlIgnoreAttribute()] bool employerIDSpecified) {
            this.Invoke("PostJob", new object[] {
                        name,
                        description,
                        duration_hours,
                        duration_hoursSpecified,
                        location,
                        reward,
                        rewardSpecified,
                        employerID,
                        employerIDSpecified});
        }
        
        /// <remarks/>
        public void PostJobAsync(string name, string description, int duration_hours, bool duration_hoursSpecified, string location, double reward, bool rewardSpecified, int employerID, bool employerIDSpecified) {
            this.PostJobAsync(name, description, duration_hours, duration_hoursSpecified, location, reward, rewardSpecified, employerID, employerIDSpecified, null);
        }
        
        /// <remarks/>
        public void PostJobAsync(string name, string description, int duration_hours, bool duration_hoursSpecified, string location, double reward, bool rewardSpecified, int employerID, bool employerIDSpecified, object userState) {
            if ((this.PostJobOperationCompleted == null)) {
                this.PostJobOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostJobOperationCompleted);
            }
            this.InvokeAsync("PostJob", new object[] {
                        name,
                        description,
                        duration_hours,
                        duration_hoursSpecified,
                        location,
                        reward,
                        rewardSpecified,
                        employerID,
                        employerIDSpecified}, this.PostJobOperationCompleted, userState);
        }
        
        private void OnPostJobOperationCompleted(object arg) {
            if ((this.PostJobCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostJobCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListOfJobs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/TempJobsWcf")]
        public Job[] ListOfJobs() {
            object[] results = this.Invoke("ListOfJobs", new object[0]);
            return ((Job[])(results[0]));
        }
        
        /// <remarks/>
        public void ListOfJobsAsync() {
            this.ListOfJobsAsync(null);
        }
        
        /// <remarks/>
        public void ListOfJobsAsync(object userState) {
            if ((this.ListOfJobsOperationCompleted == null)) {
                this.ListOfJobsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListOfJobsOperationCompleted);
            }
            this.InvokeAsync("ListOfJobs", new object[0], this.ListOfJobsOperationCompleted, userState);
        }
        
        private void OnListOfJobsOperationCompleted(object arg) {
            if ((this.ListOfJobsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListOfJobsCompleted(this, new ListOfJobsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ChangePassword", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ChangePassword([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, out bool success, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool successSpecified) {
            object[] results = this.Invoke("ChangePassword", new object[] {
                        username,
                        password});
            success = ((bool)(results[0]));
            successSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void ChangePasswordAsync(string username, string password) {
            this.ChangePasswordAsync(username, password, null);
        }
        
        /// <remarks/>
        public void ChangePasswordAsync(string username, string password, object userState) {
            if ((this.ChangePasswordOperationCompleted == null)) {
                this.ChangePasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangePasswordOperationCompleted);
            }
            this.InvokeAsync("ChangePassword", new object[] {
                        username,
                        password}, this.ChangePasswordOperationCompleted, userState);
        }
        
        private void OnChangePasswordOperationCompleted(object arg) {
            if ((this.ChangePasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangePasswordCompleted(this, new ChangePasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ApplyForJob", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ApplyForJob(int jobID, [System.Xml.Serialization.XmlIgnoreAttribute()] bool jobIDSpecified, int jobseekerID, [System.Xml.Serialization.XmlIgnoreAttribute()] bool jobseekerIDSpecified) {
            this.Invoke("ApplyForJob", new object[] {
                        jobID,
                        jobIDSpecified,
                        jobseekerID,
                        jobseekerIDSpecified});
        }
        
        /// <remarks/>
        public void ApplyForJobAsync(int jobID, bool jobIDSpecified, int jobseekerID, bool jobseekerIDSpecified) {
            this.ApplyForJobAsync(jobID, jobIDSpecified, jobseekerID, jobseekerIDSpecified, null);
        }
        
        /// <remarks/>
        public void ApplyForJobAsync(int jobID, bool jobIDSpecified, int jobseekerID, bool jobseekerIDSpecified, object userState) {
            if ((this.ApplyForJobOperationCompleted == null)) {
                this.ApplyForJobOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApplyForJobOperationCompleted);
            }
            this.InvokeAsync("ApplyForJob", new object[] {
                        jobID,
                        jobIDSpecified,
                        jobseekerID,
                        jobseekerIDSpecified}, this.ApplyForJobOperationCompleted, userState);
        }
        
        private void OnApplyForJobOperationCompleted(object arg) {
            if ((this.ApplyForJobCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ApplyForJobCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/getApplications", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/TempJobsWcf")]
        public Userdata[] getApplications(int EmployerID, [System.Xml.Serialization.XmlIgnoreAttribute()] bool EmployerIDSpecified) {
            object[] results = this.Invoke("getApplications", new object[] {
                        EmployerID,
                        EmployerIDSpecified});
            return ((Userdata[])(results[0]));
        }
        
        /// <remarks/>
        public void getApplicationsAsync(int EmployerID, bool EmployerIDSpecified) {
            this.getApplicationsAsync(EmployerID, EmployerIDSpecified, null);
        }
        
        /// <remarks/>
        public void getApplicationsAsync(int EmployerID, bool EmployerIDSpecified, object userState) {
            if ((this.getApplicationsOperationCompleted == null)) {
                this.getApplicationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetApplicationsOperationCompleted);
            }
            this.InvokeAsync("getApplications", new object[] {
                        EmployerID,
                        EmployerIDSpecified}, this.getApplicationsOperationCompleted, userState);
        }
        
        private void OngetApplicationsOperationCompleted(object arg) {
            if ((this.getApplicationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getApplicationsCompleted(this, new getApplicationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/RegistrationDatabaseUpdate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RegistrationDatabaseUpdate(int id, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string firstName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string lastName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string address, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string cantactNumbers, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string altanativeNumber, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string profileImage_string, int age, [System.Xml.Serialization.XmlIgnoreAttribute()] bool ageSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string gender) {
            this.Invoke("RegistrationDatabaseUpdate", new object[] {
                        id,
                        idSpecified,
                        userName,
                        firstName,
                        lastName,
                        address,
                        Email,
                        cantactNumbers,
                        altanativeNumber,
                        profileImage_string,
                        age,
                        ageSpecified,
                        gender});
        }
        
        /// <remarks/>
        public void RegistrationDatabaseUpdateAsync(int id, bool idSpecified, string userName, string firstName, string lastName, string address, string Email, string cantactNumbers, string altanativeNumber, string profileImage_string, int age, bool ageSpecified, string gender) {
            this.RegistrationDatabaseUpdateAsync(id, idSpecified, userName, firstName, lastName, address, Email, cantactNumbers, altanativeNumber, profileImage_string, age, ageSpecified, gender, null);
        }
        
        /// <remarks/>
        public void RegistrationDatabaseUpdateAsync(int id, bool idSpecified, string userName, string firstName, string lastName, string address, string Email, string cantactNumbers, string altanativeNumber, string profileImage_string, int age, bool ageSpecified, string gender, object userState) {
            if ((this.RegistrationDatabaseUpdateOperationCompleted == null)) {
                this.RegistrationDatabaseUpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistrationDatabaseUpdateOperationCompleted);
            }
            this.InvokeAsync("RegistrationDatabaseUpdate", new object[] {
                        id,
                        idSpecified,
                        userName,
                        firstName,
                        lastName,
                        address,
                        Email,
                        cantactNumbers,
                        altanativeNumber,
                        profileImage_string,
                        age,
                        ageSpecified,
                        gender}, this.RegistrationDatabaseUpdateOperationCompleted, userState);
        }
        
        private void OnRegistrationDatabaseUpdateOperationCompleted(object arg) {
            if ((this.RegistrationDatabaseUpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistrationDatabaseUpdateCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/TempJobsWcf")]
    public partial class CompositeType {
        
        private bool boolValueField;
        
        private bool boolValueFieldSpecified;
        
        private string stringValueField;
        
        /// <remarks/>
        public bool BoolValue {
            get {
                return this.boolValueField;
            }
            set {
                this.boolValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BoolValueSpecified {
            get {
                return this.boolValueFieldSpecified;
            }
            set {
                this.boolValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StringValue {
            get {
                return this.stringValueField;
            }
            set {
                this.stringValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System.Drawing")]
    public partial class Image {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlQualifiedName factoryTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        public System.Xml.XmlQualifiedName FactoryType {
            get {
                return this.factoryTypeField;
            }
            set {
                this.factoryTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/TempJobsWcf")]
    public partial class Job {
        
        private string descriptionField;
        
        private System.Nullable<int> duration_HoursField;
        
        private bool duration_HoursFieldSpecified;
        
        private System.Nullable<int> employer_IDField;
        
        private bool employer_IDFieldSpecified;
        
        private JobApp[] jobAppsField;
        
        private int jobIDField;
        
        private bool jobIDFieldSpecified;
        
        private string locationField;
        
        private string nameField;
        
        private System.Nullable<double> rewardField;
        
        private bool rewardFieldSpecified;
        
        private Userdata userdataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Duration_Hours {
            get {
                return this.duration_HoursField;
            }
            set {
                this.duration_HoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Duration_HoursSpecified {
            get {
                return this.duration_HoursFieldSpecified;
            }
            set {
                this.duration_HoursFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Employer_ID {
            get {
                return this.employer_IDField;
            }
            set {
                this.employer_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Employer_IDSpecified {
            get {
                return this.employer_IDFieldSpecified;
            }
            set {
                this.employer_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public JobApp[] JobApps {
            get {
                return this.jobAppsField;
            }
            set {
                this.jobAppsField = value;
            }
        }
        
        /// <remarks/>
        public int JobID {
            get {
                return this.jobIDField;
            }
            set {
                this.jobIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool JobIDSpecified {
            get {
                return this.jobIDFieldSpecified;
            }
            set {
                this.jobIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Reward {
            get {
                return this.rewardField;
            }
            set {
                this.rewardField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RewardSpecified {
            get {
                return this.rewardFieldSpecified;
            }
            set {
                this.rewardFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Userdata Userdata {
            get {
                return this.userdataField;
            }
            set {
                this.userdataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/TempJobsWcf")]
    public partial class JobApp {
        
        private int applicationIDField;
        
        private bool applicationIDFieldSpecified;
        
        private Job jobField;
        
        private System.Nullable<int> jobIdField;
        
        private bool jobIdFieldSpecified;
        
        private System.Nullable<int> jobseekerIdField;
        
        private bool jobseekerIdFieldSpecified;
        
        private Userdata userdataField;
        
        /// <remarks/>
        public int ApplicationID {
            get {
                return this.applicationIDField;
            }
            set {
                this.applicationIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ApplicationIDSpecified {
            get {
                return this.applicationIDFieldSpecified;
            }
            set {
                this.applicationIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Job Job {
            get {
                return this.jobField;
            }
            set {
                this.jobField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> JobId {
            get {
                return this.jobIdField;
            }
            set {
                this.jobIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool JobIdSpecified {
            get {
                return this.jobIdFieldSpecified;
            }
            set {
                this.jobIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> JobseekerId {
            get {
                return this.jobseekerIdField;
            }
            set {
                this.jobseekerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool JobseekerIdSpecified {
            get {
                return this.jobseekerIdFieldSpecified;
            }
            set {
                this.jobseekerIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Userdata Userdata {
            get {
                return this.userdataField;
            }
            set {
                this.userdataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/TempJobsWcf")]
    public partial class Userdata {
        
        private string emailField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private InformalSkill[] informalSkillsField;
        
        private JobApp[] jobAppsField;
        
        private Job[] jobsField;
        
        private string profileImage_StringField;
        
        private string usernameField;
        
        private string addressField;
        
        private string alternativeNumberField;
        
        private System.Nullable<int> authinticationLevelField;
        
        private bool authinticationLevelFieldSpecified;
        
        private string contactNumberField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public InformalSkill[] InformalSkills {
            get {
                return this.informalSkillsField;
            }
            set {
                this.informalSkillsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public JobApp[] JobApps {
            get {
                return this.jobAppsField;
            }
            set {
                this.jobAppsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Job[] Jobs {
            get {
                return this.jobsField;
            }
            set {
                this.jobsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProfileImage_String {
            get {
                return this.profileImage_StringField;
            }
            set {
                this.profileImage_StringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string alternativeNumber {
            get {
                return this.alternativeNumberField;
            }
            set {
                this.alternativeNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> authinticationLevel {
            get {
                return this.authinticationLevelField;
            }
            set {
                this.authinticationLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool authinticationLevelSpecified {
            get {
                return this.authinticationLevelFieldSpecified;
            }
            set {
                this.authinticationLevelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string contactNumber {
            get {
                return this.contactNumberField;
            }
            set {
                this.contactNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/TempJobsWcf")]
    public partial class InformalSkill {
        
        private string nameField;
        
        private int skill_IDField;
        
        private bool skill_IDFieldSpecified;
        
        private System.Nullable<int> userData_IDField;
        
        private bool userData_IDFieldSpecified;
        
        private Userdata userdataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int Skill_ID {
            get {
                return this.skill_IDField;
            }
            set {
                this.skill_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Skill_IDSpecified {
            get {
                return this.skill_IDFieldSpecified;
            }
            set {
                this.skill_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> UserData_ID {
            get {
                return this.userData_IDField;
            }
            set {
                this.userData_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UserData_IDSpecified {
            get {
                return this.userData_IDFieldSpecified;
            }
            set {
                this.userData_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Userdata Userdata {
            get {
                return this.userdataField;
            }
            set {
                this.userdataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetDataUsingDataContractCompletedEventHandler(object sender, GetDataUsingDataContractCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataUsingDataContractCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataUsingDataContractCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CompositeType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CompositeType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void RegistrationDatabaseCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void LgnUserCompletedEventHandler(object sender, LgnUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LgnUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LgnUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int userID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool userIDSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public bool canLogin {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public bool canLoginSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[3]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ReadEmployeesCompletedEventHandler(object sender, ReadEmployeesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadEmployeesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadEmployeesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Userdata[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Userdata[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void StoreSkillsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ReadSkillsCompletedEventHandler(object sender, ReadSkillsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadSkillsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadSkillsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InformalSkill[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InformalSkill[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ImageToBase64StringCompletedEventHandler(object sender, ImageToBase64StringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ImageToBase64StringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ImageToBase64StringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SingleUserDetailsCompletedEventHandler(object sender, SingleUserDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SingleUserDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SingleUserDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Userdata Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Userdata)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void PostJobCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ListOfJobsCompletedEventHandler(object sender, ListOfJobsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListOfJobsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListOfJobsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Job[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Job[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ChangePasswordCompletedEventHandler(object sender, ChangePasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangePasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChangePasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool success {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool successSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ApplyForJobCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void getApplicationsCompletedEventHandler(object sender, getApplicationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getApplicationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getApplicationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Userdata[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Userdata[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void RegistrationDatabaseUpdateCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591